export const TECH_STACK = [
  { name: 'React', category: 'frontend' },
  { name: 'Next.js', category: 'frontend' },
  { name: 'TypeScript', category: 'frontend' },
  { name: 'Tailwind CSS', category: 'frontend' },
  { name: 'GSAP', category: 'frontend' },
  { name: 'Framer Motion', category: 'frontend' },
  { name: 'Redux Toolkit', category: 'frontend' },
  { name: 'Zustand', category: 'frontend' },
  { name: 'Python', category: 'backend' },
  { name: 'FastAPI', category: 'backend' },
  { name: 'Node.js', category: 'backend' },
  { name: 'NestJS', category: 'backend' },
  { name: 'Express.js', category: 'backend' },
  { name: 'Django', category: 'backend' },
  { name: 'RabbitMQ', category: 'backend' },
  { name: 'BullMQ', category: 'backend' },
  { name: 'Flutter', category: 'mobile' },
  { name: 'AWS', category: 'cloud' },
  { name: 'Docker', category: 'devops' },
  { name: 'Kubernetes', category: 'devops' },
  { name: 'Terraform', category: 'devops' },
  { name: 'GitHub Actions', category: 'devops' },
  { name: 'Redis', category: 'data' },
  { name: 'PostgreSQL', category: 'data' },
  { name: 'MongoDB', category: 'data' },
  { name: 'Prisma', category: 'data' },
  { name: 'LangChain', category: 'ai' },
  { name: 'LangGraph', category: 'ai' },
  { name: 'RAG', category: 'ai' },
  { name: 'AI Agents', category: 'ai' },
  { name: 'LlamaIndex', category: 'ai' },
  { name: 'Hugging Face', category: 'ai' },
  { name: 'n8n', category: 'ai' },
] as const
